<?php
    
    $data  = $this->data;
?>
<div id="container_middle_full">
<?php if ($data):?>
    <?php echo $this->getCibleText('list_column_MAI_Title') ?>:
    <h3><?php echo($data['MAI_Title']) ?></h3>
       <p>
        <?php echo $this->getCibleText('delete_messages_confirmation')?>
           <em><b><?php echo($data['MAI_Title']); ?></b></em>?</p>
        <form action="<?php echo $this->url(array('action'=>'delete')); ?>" method="post">
            <div>
                <input type="hidden" name="blockID" value="<?php echo $data['MAI_Title']?>" />
                <input type="submit" name="delete" value="<?php echo $this->getCibleText('button_yes') ?>" />
                <input type="submit" name="cancel" value="<?php echo $this->getCibleText('button_no') ?>" />
            </div>
        </form>
<?php else:?>
        <p><?php echo $this->getCibleText('delete_message_noexist')?></p>
        <a href="<?php echo ($this->return); ?>">
            <?php echo $this->getCibleText('button_return')?>
        </a>

<?php endif;?>
</div>