<section class="news listall module block">

    <?php if ($this->params[7]) echo $this->formSelect; ?>
    <?php echo $this->showBlockTitle('h2', array('class' => 'news-title')); ?>
    <?php
    $flag = 1;
    $count = 1;
    $langSuffix = Cible_FunctionsGeneral::getLocalForLanguage(Zend_Registry::get("languageID"));
    if (count($this->paginator)):
        $itemCountPerPage = $this->paginator->getItemCountPerPage();
        ?>
        <div class="news-article-list">
            <?php
            foreach ($this->paginator as $news):
                $date_string = Cible_FunctionsGeneral::dateToString($news['ND_Date'], Cible_FunctionsGeneral::DATE_LONG);
                if ($this->detailsPageWithPaginator) {
                    $currentPageNumber = $this->paginator->getCurrentPageNumber();
                    if ($currentPageNumber > 1) {
                        $page = ($currentPageNumber - 1) * $itemCountPerPage + $count;
                        $href = $this->baseUrl() . '/' . $this->details_page . "/" . $news['ND_Date'] . "/" . $news['NI_ValUrl'] . "/page/" . $page;
                    } else
                        $href = $this->baseUrl() . '/' . $this->details_page . "/" . $news['ND_Date'] . "/" . $news['NI_ValUrl'] . "/page/" . $count;
                } else
                    $href = $this->baseUrl() . '/' . $this->details_page . "/" . $news['ND_Date'] . "/" . $news['NI_ValUrl'];
//            $last = $count == $this->paginator->getItemCountPerPage() ? ' last' : '';
                ?>

                <article class="news-article">

                    <?php if ($this->params['6']): ?>
                        <?php
                        if (!empty($news['NI_ImageSrc'])) {
                            $class = '';
                        } else {
                            $class = 'image-placeholder';
                        }
                        ?>
                        <div class='news-article-image <?php echo $class ?>'>
                            <?php
                            if (!empty($news['NI_ImageSrc'])) {
                                $normal = $this->newsImage($news['ND_ID'], $news['NI_ImageSrc'], 'medium', array('class' => 'news-article-image-image'));
                                $large = $this->newsImage($news['ND_ID'], $news['NI_ImageSrc'], 'original', array(
                                    'getSource' => true,
                                ));
                                echo $this->link($large, $normal, array('class' => 'news-article-image-link thumbnail prettyPhoto'));
                                ?>
                            <?php } ?>
                        </div>
                    <?php endif; ?>
                    <header class='news-article-header content'>
                        <?php if ($this->params['5']): ?>
                            <div class="news-article-date date"><?php echo $date_string; ?></div>
                        <?php endif; ?>

                        <h1 class="news-article-title">
                            <?php echo $this->link($href, $news['NI_Title'], array('title' => $this->getClientText('see_details_news_text'))); ?>
                        </h1>
                    </header>


                    <div class="news-article-content content">
                        <?php
                        $text = '';
                        $showNext = true;
                        if ($this->params['3'] && !empty($news['NI_Brief'])) {
                            $text = $news['NI_Brief'];
                        } elseif ($this->params['3'] && empty($news['NI_Brief'])) {
                            $text = Cible_FunctionsGeneral::html2text($news['NI_Text']);
                            $text = Cible_FunctionsGeneral::truncateString($text, 150);
                        } else
                            $showNext = false;


                        if ($this->paginator->getItemCountPerPage() != $flag) :
                            $flag++;
                            ?>
                        <?php endif; ?>

                        <?php if (!empty($text)): ?>
                            <p class="news-article-brief">
                                <?php echo $text; ?>
                            </p
                        <?php endif; ?>
                        <div class="news-article-navigation">
                            <?php if ($showNext): ?>
                                <?php
                                echo $this->link(
                                        $href, $this->getClientText('see_details_news_text'), array(
                                    'title' => $this->getClientText('see_details_news_text'),
                                    'class' => 'link-button news-article-link-button'
                                        )
                                );
                                ?>
                            <?php endif; ?>
                        </div>
                </article>
                <?php
                if ($this->paginator->getItemCountPerPage() != $flag) :
                    $flag++;
                    ?>
                    <?php
                endif;
                $count++
                ?>
            <?php endforeach; ?>
        </div>
        <div class="pagination">
            <?php echo $this->paginationControl($this->paginator, 'sliding', 'partials/products.paginator.phtml'); ?>
        </div>
    <?php else: ?>
        <div class="news-no-article">
            <?php if ($this->otherData): ?>
                <?php $options = array('type' => 'page', 'message' => $this->getClientText('empty_data_disclaimer')); ?>
                <p><?php echo $this->languageSwitcher($options); ?></p>
            <?php else: ?>
                <p><?php echo $this->getCibleText('news_no_news') ?></p>
            <?php endif; ?>
        </div>
    <?php endif; ?>
</section>
<?php echo $this->partial('partials/filterDates.phtml'); ?>

<?php $this->placeholder('footerScript')->captureStart(); ?>
<script type="text/javascript">
//<![CDATA[
    $(document).ready(function() {

        $('.news1col').click(function() {
            window.location.href = $(this).find('a').attr('href');
        });
    });
//]]>
</script>
<?php $this->placeholder('footerScript')->captureEnd(); ?>
