<?php
// One place_holder template, so grab only the first place_holder elements
$ph1_blocks = isset($this->blocks[1]) ? $this->blocks[1] : array();
$ph2_blocks = isset($this->blocks[2]) ? $this->blocks[2] : array();
$ph3_blocks = isset($this->blocks[3]) ? $this->blocks[3] : array();
$controller = 'manage';
?>
<div id="template" style="width: 958px">
    <div style="clear: both; width: 97%; margin: 1%;" class="zone1">
        <!-- Placeholder 1 = special banners -->
        <?php
        $options = array(
            'zoneId' => 1,
            'rows' => $ph1_blocks,
            'controller' => $controller,
            'isActive' => false
        );
        ?>
        <?php echo $this->zonesTemplate($options); ?>
    </div>
    <div style="clear: both; width: 97%; margin: 1%;" class="zone2">
        <!-- Placeholder 2 -->
        <?php
        $options = array(
            'zoneId' => 2,
            'rows' => $ph2_blocks,
            'controller' => $controller,
            'isActive' => true
        );
        ?>
        <?php echo $this->zonesTemplate($options); ?>
    </div>
    <div style="width: 97%; margin: 1%;float: left;" class="zone3 blackZone">
        <!-- Placeholder 3 = special banners -->
        <?php
        $options = array(
            'zoneId' => 3,
            'rows' => $ph3_blocks,
            'controller' => $controller,
            'isActive' => true
        );
        ?>
        <?php echo $this->zonesTemplate($options); ?>
    </div>    
</div>