<?php
$moreClasses = '';
if ($this->step > 1)
    $backButtonLabel = 'form_label_prev_step_btn';
else
    $backButtonLabel = 'btn_cart_add_another';

if ($this->step > 2)
    $customSubmitLabel = 'form_label_confirm_order_btn';
else
    $customSubmitLabel = 'form_label_next_step_btn';

if (isset($this->moreClass))
    $moreClasses = $this->moreClass;
?>
<div class='module-pagination pagination'>
    <ul id="cart-big-buttons" class="module-paginatio-list pagination-list <?php echo $moreClasses; ?>">
        <?php if (!empty($this->urlBack)): ?>
            <li class="module-navigation-arrow module-navigation-previous">
                <a href="<?php echo $this->urlBack; ?>"><?php echo $this->getClientText($backButtonLabel) ?></a>
            </li>
        <?php endif; ?>

        <?php if (!empty($this->itemCount)): ?>
            <li class="module-navigation-arrow module-navigation-next">
                <a id="stepToNext" href="#"><?php echo $this->getClientText("form_label_paypal_pay") ?></a>
            </li>
        <?php endif; ?>

        <?php if (!empty($this->customNext)): ?>
            <li class="module-navigation-arrow module-navigation-next">
                <a id="stepTopNext" href="#" class="<?php echo $this->customNext ?>"><?php echo $this->getCibleText($customSubmitLabel) ?></a>
            </li>
        <?php endif; ?>
        <?php if (!empty($this->customSubmit)): ?>
            <li class="module-navigation-arrow module-navigation-submit">
                <button id="toexternalpage" class="<?php echo $this->customSubmit ?> button-submit"><?php echo $this->getCibleText($customSubmitLabel) ?></button>
            </li>
        <?php endif; ?>

    </ul>
</div>
<script type="text/javascript">
    //<![CDATA[
    // Permet du soumettre le formulaire en simulant le clique sur le submit
    $(document).ready(function() {
        $('#stepToNext').click(function(e){
            e.preventDefault();
            $('#submit').click();
        });
        $('a#stepToNext').click(function(e){
            e.preventDefault();
            $('#submit').click();
        });
    });

    //]]>
</script>