<?php $_viewscript = $this->viewscript ? $this->viewscript : 'partials/imagesList.paginator.phtml'; ?>
<div class="searchable-list">
    <div id="form_panel" class="list">
        <?php if (count($this->paginator)): ?>
            <?php $i = 1; ?>
            <?php foreach ($this->paginator as $item): ?>
                <?php $i == 0 ? $i = 1 : $i = 0; ?>
                <?php
                $id = $item[$this->field_list['idField']];
                $img = $item[$this->field_list['filenameField']];
                ?>
                <div class="image images-boxes">
                    <?php
                    $url = $this->url(array('img' =>$id));
                    $image = $this->moduleImage(
                        $this->moduleName, $id, $img, $this->field_list['format'], array('class' => '')
                    );
                    echo $this->link($url,$image);
                    ?>
                    <?php echo $this->link($url, $this->clientImage('target-mouse-over.png', array('border' => 0, 'class' => 'target-mouse'))); ?>
                </div>
            <?php endforeach; ?>
            <?php
        else:
            echo $this->getCibleText('fo_gallery_information_message_noGallery');
        endif;
        ?>
    </div>
    <?php echo $this->paginationControl($this->paginator, 'sliding', $_viewscript); ?>
</div>

<?php
$idsList = array();
if (!empty($_SESSION['idsList']))
    $idsList = $_SESSION['idsList'];
?>
