<?php

if (!empty($this->category))
    $headerText = str_replace('##CATEGORY##', $this->category, $this->getCibleText('header_edit_'.$this->cleaction.'_text'));
else
    $headerText = $this->getCibleText('header_edit_'.$this->cleaction.'_text');

echo $this->partial('partials/header.pageDetails.phtml', array(
    'pageTitle' => $headerText,
    'pageDescription' => $this->getCibleText('header_edit_'.$this->cleaction.'_description'),
    'breadcrumb' => ''
));
;
?>
<div id="default_form">
    <div id="form_panel">
        <?php echo($this->form);?>
    </div>
</div>
<script type="text/javascript">
    //<![CDATA[
    var wwwPath = '<?php echo Zend_Registry::get('www_root')?>';
    $(document).ready(function(){
        $().manageImg({
            baseUrl: "<?php echo $this->BaseUrl()?>",
            imgList: <?php echo $this->moreImg?>,
            imagesPath: "<?php echo $this->imagesPath?>"
        });
    });
    //]]>
</script>
<?php echo $this->partial("partials/formatField.phtml", array('locale' => $this->locale)); ?>