<?php
$cartTotalCount = $this->cartTotal;
$session = Zend_Session::namespaceGet('order');

?>
<section class="block cart-details summary">
    <?php echo $this->partial('partials/paypalinfo.phtml', 'catalog'); ?>
        <div id="product-list" class="">
            <div class="headerProductList row hidden-xs">
                <div class="col-lg-8">
                    <p class="col-lg-2">&nbsp;</p>
                    <p class="col-lg-10"><?php echo $this->getClientText('product_label'); ?></p>
                </div>
                <div class="col-lg-4 text-center">
                    <p class="col-lg-4"><?php echo $this->getClientText('form_item_qty_label'); ?></p>
                    <p class="col-lg-4"><?php echo $this->getClientText('unit_price_label'); ?></p>
                    <p class="col-lg-4 text-right"><?php echo $this->getClientText('cart_item_total_label'); ?></p>
                </div>
            </div>
    <?php if(!empty($this->productData)): ?>
        <?php foreach ($this->productData as $cartId => $product):?>
        <?php
            $currProd  = $product['data'];
            $currItem  = $product['items'];
            $productId = $currProd['P_ID'];
            $disable   = isset($product['cart']['disable'])?$product['cart']['disable']:array();
            $promo     = $product['cart']['promoId'];
            $itemId    = $currItem['I_ID'];
            if (!$disable):
                $labelPromo = $promo > 0 ?$this->getClientText('alert_special_offer_item') : '';
        ?>
            <article class="row">
                <div class="col-xs-12 col-md-8">
                    <figure class="product-img col-xs-12 col-lg-2">
                        <?php
                        echo $this->moduleImage('catalog',
                            'products/' . $productId,
                            $currProd['P_Photo'], 'thumb',
                            array(
                                'class'   => 'smallThumb img-responsive',
                                'alt' => $currProd['P_Photo'],
                                'useSize' => false,
                                'prettyPhoto'=>array(
                                    'size'  => 'original',
                                    'image' => $currProd['P_Photo'])
                                    )
                            );
                        ?>
                    </figure>
                    <figcaption class="product-description col-xs-12 col-lg-10">
                        <p class="">
                            <span class="product-item-label"><?php echo $currProd['PI_Name'] . ' | ' . $currItem['II_Name'] ?></span>
                            <br /><span class="alertSpecial"><?php echo $labelPromo ; ?></span>
                        </p>
                    </figcaption>
                </div>
                <div class="col-xs-12 col-lg-4">
                    <?php echo $currItem['render']; ?>
                </div>
            </article>
        <?php endif; ?>
        <?php endforeach;?>
        </div>
        <div class="totalSummary row">
            <div class="info-data col-xs-12 col-lg-7">
            <?php if(!empty($session['order']['nbPoint'])): ?>
                <?php echo $this->getClientText('cart_label_bonus_points', null,
                    array('replace' =>
                        array('XX' => $session['order']['nbPoint'])));
                ?>
            <?php endif; ?>
            <?php if ($this->parameters['limitTpsFee'] >= 0): ?>
                <p class="infoTpsFees">
                <?php echo $this->getClientText('cart_label_tpFees_limit', null,
                    array('replace' =>
                    array('##TP_FEES_LIMIT##' => $this->parameters['limitTpsFee']))); ?>
                </p>
            <?php endif; ?>
            <?php if (empty($this->parameters['tpsFee'])): ?>
                <p class="tps-included">
                    <?php echo $this->getCibleText('cart_label_tpFees_included'); ?>
                </p>
            <?php endif; ?>
            <?php if ($session['order']['limitOrder'] > 0
                    && $session['order']['subTotal'] > $session['order']['limitOrder']): ?>
                <p class="infoLimitOrder infoTpsFees">
                    <?php
                    echo $this->getClientText('cart_label_order_limit', null,
                        array('replace' =>
                            array('##TP_ORDER_LIMIT##' => $this->parameters['limitOrder']))
                        );
                    ?>
                </p>
            <?php endif; ?>
            <?php if ($this->parameters['includeTaxs'] == 1): ?>
                <p class="infoTaxesIncluded">
                <?php echo $this->getCibleText('cart_label_taxes_included'); ?>
                </p>
            <?php endif; ?>
            </div>
            <div class="col-xs-12 col-lg-5 text-right">
                <p id="zoneTitle" class="col-xs-12 col-lg-12 force-right">
                    <span class="bold-secondary">
                    <?php echo $this->getClientText('cart_summary_title'); ?>
                    </span>
                </p>
                <p id="subTotalLbl" class="col-xs-9 col-lg-9">
                    <?php echo $this->getClientText('cart_summary_subtotal'); ?>
                </p>
                <p id="subTotalValue" class="col-xs-3 col-lg-3 number">
                    <span><?php echo sprintf('%.2f', $session['order']['subTotal']); ?></span> $
                </p>
                <p id="transportLbl" class="col-xs-9 col-lg-9">
                    <?php echo $this->getClientText('cart_transport_label'); ?>
                </p>
                <p id="transportValue" class="col-xs-3 col-lg-3 number">
                    <?php if(Cible_FunctionsGeneral::compareFloats(
                        $session['order']['subTotal'], '<', $session['order']['limitShip'], 2)
                        || $session['order']['limitShip'] < 0) : ?>
                    <span><?php echo sprintf('%.2f', $session['order']['shipFee']) ?></span> $
                    <?php else: ?>
                    <span>0.00</span> $
                    <?php endif; ?>
                </p>
                <?php
                $classInfo = '';
                if ((bool)$session['order']['includeTaxs'] && $session['order']['subTotProv'] > 0):
                    $classInfo = 'text-info';
                ?>
                <p id="subTotalLbl" class="col-xs-9 col-lg-9 <?php echo $classInfo; ?>">
                    <?php echo $this->getCibleText('cart_summary_subtotal_before_tax'); ?>
                </p>
                <p id="subTotalValue" class="col-xs-3 col-lg-3 number <?php echo $classInfo; ?>">
                    <span><?php echo sprintf('%.2f', $session['order']['subTotProv']); ?></span> $
                </p>
                <?php endif; ?>
                <p id="tvqLbl" class="col-xs-9 col-lg-9 <?php echo $classInfo; ?>">
                    <?php if (isset($this->parameters['taxeFed'])
                        && $this->parameters['taxeFed'] > 0): ?>
                        <?php echo $this->getClientText('cart_tvq_label'); ?>
                    <?php else: ?>
                        <?php echo$this->parameters['taxeCode'];?>
                    <?php endif; ?>
                </p>
                <?php if ($session['order']['taxProv'] > 0): ?>
                <p id="tvqValue"class="col-xs-3 col-lg-3 number <?php echo $classInfo; ?>">
                    <span><?php echo sprintf('%.2f',
$session['order']['taxProv']); ?></span> $
                </p>
                <?php endif; ?>
                <?php if ($session['order']['taxFed'] > 0): ?>
                <p id="tpsLbl" class="col-xs-9 col-lg-9 <?php echo $classInfo; ?>">
                    <?php echo $this->getClientText('cart_tps_label'); ?>
                </p>
                <p id="tpsValue" class="col-xs-3 col-lg-3 number <?php echo $classInfo; ?>">
                    <span><?php echo sprintf('%.2f', $session['order']['taxFed']); ?></span> $
                </p>
                <?php endif; ?>
                <p id="totalLbl" class="col-xs-9 col-lg-9 bold-secondary">
                    <?php echo $this->getClientText('cart_total_label'); ?>
                </p>
                <p id="totalValue" class="col-xs-3 col-lg-3 number bold-secondary">
                    <?php echo sprintf('%.2f', $session['order']['charge_total']) ?> $
                </p>
            </div>
        </div>
    <?php else : ?>
        <div id="no-item"><?php echo $this->getClientText('cart_no_item') ?></div>
    <?php endif; ?>
</section>
