<?php
echo $this->partial('partials/header.pageDetails.phtml', array(
    'pageTitle' => $this->getCibleText('header_add_background_text'),
    'pageDescription' => $this->getCibleText('header_add_background_description'),
    'breadcrumb' => ''
));                
?>

<div id="default_form">
    <div id="form_panel">
        <?php echo($this->form);?>        
    </div>                    
</div>


<?php //include("cropImage.phtml"); ?>

