<?php $myProfileLink = Cible_FunctionsPages::getPageLinkByID(5);?>
<div id="cart" class="block order-summary">
    <?php echo $this->partial('partials/stepTopLine.phtml', 'cart' ,array('step' => $this->step)); ?>
    <span class="subtitles">
    <?php echo $this->getClientText('order_summary_products_title'); ?>
    </span>
    <?php echo $this->action('cartdetails', 'index', 'cart'); ?>
    <div class="clear_both"><?php echo $this->clientImage('pix.gif', array('alt'=>'')); ?></div>
    <!--<span class="subtitles newAccount">-->
    <?php // echo $this->getClientText('order_resume_account_data_title'); ?>
    <!--</span>-->
    <!--<hr />-->
    <?php $userData = $this->memberInfos;?>
    <div class="block">
        <?php echo $this->formOrder; ?>
    </div>
    <?php $class = 'stepBottom';?>
    <?php
    echo $this->partial('partials/cartNavigationLinks.phtml', 'cart',
        array(
            'urlBack'  => $this->urlBack,
            'nextStep' => $this->nextStep,
            'step'     => $this->step,
            'customNext'=> 'customNext',
            'moreClass'=> 'stepTwoBottom'
            )
        );
    ?>
</div>