<script type="text/javascript">
    //<![CDATA[
    $(document).ready(function(){

        if($("a.prettyPhoto").length > 0 )
        {
            $("a.prettyPhoto").prettyPhoto({
                show_title:true,
                animation_speed:'normal',
                theme:'facebook',
                slideshow:false,
                autoplay_slideshow: false,
                overlay_gallery:false
            });

        }
    });
//]]>
</script>