<?php
echo $this->partial('partials/header.pageDetails.phtml', array(
    'pageTitle' => $this->getCibleText('header_modify_header_text'),
    'pageDescription' => $this->getCibleText('header_modify_header_description'),
    'breadcrumb' => ''
));                
?>
<div id="default_form">
    <div id="form_panel">
        <?php echo($this->form);?>        
    </div>                    
</div>
<?php 
  //  include("cropImage.phtml");
?>