<?php
$langSuffix = Cible_FunctionsGeneral::getLocalForLanguage(Zend_Registry::get("languageID"));
$date = new Zend_Date($this->parution_date, null, $langSuffix);
$date_string = Cible_FunctionsGeneral::dateToString($date, Cible_FunctionsGeneral::DATE_LONG_NO_DAY, '.');
$date_string_url = Cible_FunctionsGeneral::dateToString($date, Cible_FunctionsGeneral::DATE_SQL, '-');
?>
<section class="newsletter details module">
    <h1 class="newsletter-details-title">
        <?php
        echo($this->parution_title);
        ?>
    </h1>
    <?php
    if ($this->articles) {
        foreach ($this->articles as $article) {
            ?>
            <article class="newsletter-details-article content">
                <h2 class="newsletter-details-article-title">
                    <?php
                    $this->headTitle($article['NA_Title']);
                    echo $article['NA_Title'];
                    ?>
                </h2>
                <?php
                //echo $date_string;
                ?>
                <?php if ($article['NA_ImageSrc']) { ?>
                    <div class="newsletter-news-image image-placeholder">  
                        <?php
                        $large = $this->moduleImage(
                                'newsletter', $article['NA_ReleaseID'] . "/" . $article['NA_ID'], $article['NA_ImageSrc'], 'medium', array('class' => 'news-article-image-image', 'getSource' => true));
                        $normal = $this->moduleImage(
                                'newsletter', $article['NA_ReleaseID'] . "/" . $article['NA_ID'], $article['NA_ImageSrc'], 'medium', array('class' => 'newsletter_photo news_photo_list', 'border' => '0'));
                        echo $this->link($large, $normal, array('class' => 'newsletter-article-image-link thumbnail prettyPhoto'));
                        ?>
                    </div>
                    <?php
                }
                if ($article['NA_Text']) {
                    ?>
                    <div class='newsletter-news-content'>
                        <?php
                        echo $this->decorateImage($article['NA_Text']);
                        ?>
                    </div>
                    <?php
                }
                ?>
            </article>
            <?php
        }
    }
    ?>
    <nav class="newsletter-options">
        <div class="newsletter-details-article-return">
            <a class="link-button" href="<?php echo $this->baseUrl() . '/' . $this->back_to_release . "/" . $date_string_url . "/" . $this->parutionURL ?>" title="<?php echo $this->getClientText('see_details_news_text') ?>">
             <!--<a href="<?php echo $this->back_to_release; ?>">-->
<?php echo($this->getCibleText('newsletter_button_return_to_newsletter')); ?>
            </a>
        </div>
<?php /*
        <a href="<?php echo $this->subscribeLink; ?>">
<?php echo($this->getCibleText('newsletter_button_subscribe')); ?>
        </a>

        <a href="<?php echo $this->unsubscribeLink; ?>">
<?php echo($this->getCibleText('newsletter_button_unsubscribe')); ?>
        </a>

        <a href="<?php echo $this->archivesLink; ?>">
<?php echo($this->getCibleText('newsletter_button_archives')); ?>
        </a>
 * */ ?>
    </nav>
</section>