<?php
$this->headTitle($this->title);
$this->pageTitle($this->title);
?>
<section id="contentCatalog" class="block catalog">
    <?php foreach ($this->paginator as $name => $data): ?>
        <article class="list col-lg-4">
            <?php
            $name = $data["PI_Name"];
            $url = $this->Url(array('action' => null)) . '/' . $this->stringUrl . '/' . $data['PI_ValUrl'];
            ?>
            <figure class="picture">
                <?php $img = $this->clientImage('logo.png'); ?>
                <?php if (!empty($data['P_Photo'])) : ?>
                <?php $img = $this->moduleImage(
                            'catalog', 'products/' . $data['P_ID'],
                            $data['P_Photo'], 'thumb');
                ?>
                <?php endif; ?>
                <?php echo $this->link($url, $img); ?>
            </figure>
            <p class="text">
                <?php // echo $data['CCI_Description']; ?>
                <?php echo $this->link($url, $name, array('class' => '')); ?>
            </p>
        </article>
        <?php endforeach;?>
    <div class="clear_both"></div>
    <?php echo $this->paginationControl($this->paginator,'sliding', 'partials/products.paginator.phtml'); ?>
</section>
