<?php $controllerName = $this->request->getParam('controller'); ?>
<?php
$i = 1;
$columns = 2;
$this->headTitle($this->title);
$this->pageTitle($this->title);
?>
<div id="contentCatalog" class="block catalog">
    <?php foreach ($this->paginator as $name => $data): ?>
        <?php $class = ($i % $columns == 0) ? 'right' : 'left'; ?>
        <div class="list <?php echo $class; ?>">
            <?php
            $name = $data["PI_Name"];
            $url = $this->Url(array('action' => null)) . '/' . $this->stringUrl . '/' . $data['PI_ValUrl'];
            ?>
            <p class="picture">
                <?php if (!empty($data['P_Photo'])) : ?>
                <?php echo $this->link($url,
                        $this->moduleImage(
                            'catalog', 'products/' . $data['P_ID'], $data['P_Photo'], 'medium'
                        )
                    );
                ?>
                <?php else: ?>
                    <?php echo $this->clientImage('logo.png'); ?>
                <?php endif; ?>
            </p>
            <p class="text">
                <?php // echo $data['CCI_Description']; ?>
                <?php echo $this->link($url, $name, array('class' => '')); ?>
            </p>
        </div>
        <?php
        $i++;
    endforeach;
    ?>
    <div class="clear_both"></div>
    <?php echo $this->paginationControl($this->paginator,'sliding', 'partials/products.paginator.phtml'); ?>
</div>
