
<?php
$random = rand(1, 100000000);
if ($this->imageToShow):
    ?>
    <section class="banners index module">
        <?php
        echo $this->showBlockTitle('h2', array('class' => 'banners-title'));
        $alt = "banners";
        if (!empty($this->bannersGroup[0]['BG_Name'])) {
            $alt = $this->bannersGroup[0]['BG_Name'];
        }
        ?>
        <div id="slideshow-<?php echo $random; ?>" class="banners-container">
            <?php foreach ($this->imageToShow as $index => $image):
                ?>
                <div class="banners-slide banners-slide-<?php echo $image['color']; ?>">
                    <?php
                    $content = '';
                    if (!empty($image['text']))
                        $content .= '<div class="banners-container container"><div class="banners-content content">' . $image['text'] . '</div></div>';
                    if ($this->navi)
                        $content .= '<div class="cycle-pager banners-nav"></div>';
                    if (!empty($image['img'])){
                        $img = $this->image($image['img'], array('alt' => $alt, 'class' => 'banners-image', 'direct' => true));
                        if (!empty($image['url'])){
                            $content .= $this->link($image['url'], $img, array("class" => "banners-link popup-youtube"));
                        }else{
                            $content .= $img;
                        }
                    }
                    if (empty($image['url'])){
                        $content = '<div class="banners-nolink">' . $content . '</div>';
                    }
                    echo $content;
                    ?>
                </div>
            <?php endforeach; ?>
        </div>



        <?php if (Zend_Registry::isRegistered('bannerLinkMore')): ?>
            <div class="moreBanners">
                <span class="suite_arrow">
                    <?php $pageIndexName = Zend_Registry::get('bannerLinkMore'); ?>
                    <a href="/<?php echo $pageIndexName; ?>">
                        <?php echo $this->getCibleText('moreBannersText'); ?>
                    </a>
                </span>
            </div>
        <?php endif; ?>
    </section>
<?php endif; ?>
<?php $this->placeholder('footerScript')->captureStart(); ?>

<script type="text/javascript">
//<![CDATA[
    $(window).load(function() {
        var $slideshow = $('#slideshow-<?php echo $random; ?>');
        $slideshow.cycle({
        autoHeight:'calc',
                fx: "<?php echo $this->effect ?>",
<?php if ($this->navi) : ?>
            prev : '.leftCycle-<?php echo $random; ?>',
                    next : '.rightCycle-<?php echo $random; ?>',
<?php endif; ?>
        slides : "> .banners-slide",
                pager: '.cycle-pager',
                speed : <?php echo $this->delais * 1000 ?>,
                timeout : <?php echo ($this->autoPlay) ? $this->transition : 0 ?>,
                //manualTrump:false,
                log: false
    });
    }).resize();
    $('.popup-youtube').magnificPopup({
          disableOn: 700,
          type: 'iframe',
          mainClass: 'mfp-fade',
          removalDelay: 160,
          preloader: false,

          fixedContentPos: false
        });
//]]>
</script>
<?php $this->placeholder('footerScript')->captureEnd(); ?>
