<?php $newAccountUrl = Cible_FunctionsCategories::getPagePerCategoryView(1, 'login', 17, null, false); ?>
<?php $cartUrl = $this->baseUrl() . '/' . 'cart/index/ajax/'; ?>
<?php $loginUrl = $this->baseUrl() . '/' . 'catalog/index/login/'; ?>
<?php // $dispCartUrl = $this->baseUrl() . '/' . 'cart/index/cart/'; ?>
<?php $baseUrl = $this->baseUrl(); ?>
<?php $langId = Zend_Registry::get('languageID'); ?>
<?php $user = Zend_Registry::get('user'); ?>
<?php $isLogIn = $user ? 1 : 0; ?>
<?php $hiddenLogin = $isLogIn ? 'hidden' : ''; ?>
<?php $hiddenCart = $isLogIn ? '' : 'hidden'; ?>
<?php // $link = $this->link($baseUrl . $newAccountUrl, $this->getCibleText('form_account_button_submit'), array('class' => 'button-submit')); ?>
<div class="modal fade " id="login-cart">
    <div class="modal-dialog <?php echo ($isLogIn) ? '' : 'modal-lg' ?> ">
        <div class="modal-content">
            <input type="hidden" id="isLogIn" value="<?php echo $isLogIn; ?>">
            <div class="modal-body row <?php echo $hiddenLogin; ?>">
                <div class="modal-form content col-md-6">
                    <h5><?php // echo $this->getClientText('login_form_login_title'); ?></h5>
                    <?php echo $this->action('login', 'index', 'catalog', array()); ?>
                </div>
                <div class="modal-register-text content col-md-6">
                    <h5><?php echo $this->getClientText('quoteRequest_account_introduction_text'); ?></h5>
                    <br />
        <?php
        echo $this->link('/' . Cible_FunctionsCategories::getPagePerCategoryView(1,
            'become_client', 17, null, true),
            $this->getCibleText('form_select_option_view_order_become_client'),
            array('class' => 'link-button'));
 ?>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        var isLogIn = <?php echo $isLogIn ?>;
        defaultProperties.setCartUrl('<?php echo $cartUrl ?>');
        defaultProperties.setLangId('<?php echo $langId ?>');
        defaultProperties.setBaseUrl('<?php echo $baseUrl ?>');

//        if (isLogIn) {
            updateCart('<?php echo $cartUrl; ?>', 'refresh');
//        }
        var link = {};
        var isProductLoading = false;
        var link = {};
        $('.login-btn').click(function(e) {
            e.preventDefault();
            if (!isProductLoading) {
                isProductLoading = true;
                $('#login-cart').appendTo('body').modal('show');
            }
        });
        $('#login-cart').on('click', '#submit_login', function(e) {
            e.preventDefault();
            var data = $(this).parents('form').serialize();
            $.post(
                '<?php echo $loginUrl ?>',
                data,
                function(result) {
                    if (result > 0) {
                        $('#isLogIn').val(result);
                        window.location.reload();
//                        $('.modal-body, .modal-title').toggleClass('hidden');
//                        $('.modal-dialog').removeClass('modal-lg');
                    } else {
                        $('.modal-body .modal-form .block').not(':hidden').html(result);
                        $('.modal-dialog').addClass('modal-lg');
                    }
                }
            );
        });
        $('.add-to-cart').click(function(e) {
            e.preventDefault();
            link = $(this);
            $(this).addClass('loading').attr('disabled', true);
            var info = link.attr('data-order-id').split("-");
            var quantite = 1;
            var pId = info[0];
            var itemId = info[1];
            addToCart('<?php echo $cartUrl; ?>', pId + '-' + itemId + '-' + quantite, '<?php echo $langId; ?>');
            return false;

        });
    });
</script>