<script type="text/javascript">
    //<![CDATA[
    $(document).ready(function(){
        var locale = '<?php echo $this->locale ?>';
        $('.decimal').live('blur', function (){
            $(this).parseNumber({format:"#,###.00", locale:locale});
            $(this).formatNumber({format:"#,###.00", locale:locale});
        });
        $('.integer').live('blur',  function (){
            $(this).parseNumber({format:"#,###", locale:locale});
            $(this).formatNumber({format:"#,###", locale:locale});
        });

    });
    $(window).load(function(){
        var locale = '<?php echo $this->locale ?>';
        $('.decimal').each(function(){
            $(this).parseNumber({format:"#,###.00", locale:locale});
            $(this).formatNumber({format:"#,###.00", locale:locale});
        })
        $('.integer').each(function(){
            $(this).parseNumber({format:"#,###", locale:locale});
            $(this).formatNumber({format:"#,###", locale:locale});
        })
    });
    //]]>
</script>