<script type="text/javascript">
    //<![CDATA[
    $(document).ready(function(){
        $('.manageData').valuesList({
            baseUrl : '<?php echo $this->baseUrl(); ?>',
            refresh: false,
            msgAlert: "<?php echo $this->getCibleText('references_delete_inuse_alert'); ?>"
        });
    });
    //]]>
</script>
<!--<div id="dialogForm" title="" style="display:none"></div>-->
<div id="dialogConfirm" title="" style="display:none"></div>
