
<?php if ($this->message): ?>
<span class="subtitles">
    <?php echo $this->message ?>
</span>
<?php else: ?>
<span class="subtitles">
    <?php echo $this->getClientText('login_form_login_title') ?>
</span>
<?php endif; ?>
<?php if( isset($this->error) ): ?>
    <p id="login_error" class="alert alert-danger" role="alert">
        <!--<span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>-->
        <!--<span class="sr-only"></span>-->
        <?php echo $this->error ?>
    </p>
<?php endif; ?>
<?php echo $this->form; ?>
<div id="forgot-password">
    <?php echo $this->link('javascript:toggleLostPassword();', $this->getClientText('lost_password_link')) ?>
</div>
<div id="lostPasswordPanel" style="display: none">
    <div id="lostPasswordPanel-content">
        <div id="request-form">
            <?php echo $this->getCibleText('form_label_email') ?>&nbsp;<?php echo $this->formText('lostPasswordEmail', '', array('class'=>'stdTextInput')) ?>
            <?php echo $this->formButton('lostPasswordButton', $this->getCibleText('button_submit'), array('class'=>'button','onclick'=>'javascript:retrievePassword();')) ?>
        </div>
        <div id="emailValidatorEmpty" class="errors"><?php echo $this->getCibleText('validation_message_empty_field') ?></div>
        <div id="emailValidatorError" class="errors"><?php echo $this->getClientText('lost_password_email_validation_error') ?></div>
        <div id="systemError" class="errors"></div>
    </div>
</div>