<div id="lostPasswordPanel" class="lostPasswordPanel" style="display: none">
    <div id="lostPasswordPanel-content">
        <div id="request-form">
            <label><?php echo $this->getCibleText('form_label_email') ?></label>&nbsp;<?php echo $this->formText('lostPasswordEmail', '', array('class'=>'stdTextInput')) ?>
            <?php echo $this->formButton('lostPasswordButton', $this->getCibleText('button_submit'), array('class'=>'button small','onclick'=>'javascript:retrievePassword();')) ?>
        </div>
        <div id="emailValidatorEmpty" class="errors"><?php echo $this->getCibleText('validation_message_empty_field') ?></div>
        <div id="emailValidatorError" class="errors"><?php echo $this->getClientText('lost_password_email_validation_error') ?></div>
        <div id="systemError" class="errors"></div>
    </div>
</div>