<?php
$section = $this->section;
$lang = $this->view->languageId;
$baseUrl = Zend_Registry::get('web_root');
$config = Zend_Registry::get('config');
$edith_logo = $this->link('#', $this->clientImage('logo.png', array('alt' => "Edith", 'title' => "Edith", 'class' => 'site-footer-logo-image'), array('class' => 'site-footer-logo')));
$array_replace = array('<p>' => '', '<P>' => '', '</p>' => '', '</P>' => '',
    '%%%GET_DATE_YEAR%%%' => date('Y'),
    '%%%SITE_NAME%%%' => $config->site->title->$lang);
$copyrightText = $this->getClientText('footer_copyright', null, $array_replace);

$imageFirstALT = "";
if (Zend_Registry::isRegistered('altImageFirst')) {
    $imageFirstALT = Zend_Registry::get('altImageFirst');
}
if ($imageFirstALT == "") {
    if (Zend_Registry::isRegistered('pageTitle')) {
        $imageFirstALT = Zend_Registry::get('pageTitle');
    } else if ($imgAlt != "") {
        $imageFirstALT = $imgAlt;
    } else {
        $imageFirstALT = $config->site->title->$lang;
    }
}
?>
<div class="site-footer-top">
    <div class="site-footer-top-container container">
        <div class="site-footer-logo col-md-4">
            <?php
            $homeDetails = Cible_FunctionsPages::getHomePageDetails();
            $logo = $config->clientLogo->src;
            echo $this->link(
                    $this->baseUrl() . '/' . $homeDetails['PI_PageIndex'], $this->clientImage($logo, array('alt' => $imageFirstALT, 'class' => '')), array('title' => $imageFirstALT, 'class' => 'site-footer-logo-image')
            );
            ?>
        </div>
        <div class="site-footer-facebook col-md-4">
            <?php echo $this->getClientText('footer_facebook') ?>
        </div>
        <div class="site-footer-collab col-md-4">
            <h3 class="title-footer"><?php echo $this->getClientText('footer_title_collab') ?></h3>
            <?php echo $this->getClientText('footer_collab') ?>
        </div>
    </div>
</div>
<div class="site-footer-bottom">
    <div class="site-footer-bottom-container container">
        <span class="site-footer-copyright-text">
            <?php echo $copyrightText; ?>
        </span>
        <?php echo $this->menu('footer', array('parentIdAlt' => 'footer1ParentId', 'class' => 'site-footer-menu')) ?>
    </div>
</div>
<?php
$config = Zend_Registry::get('config');
if ($config->zIndexCalculator->embeded):
    ?>
    <script type="text/javascript" src="<?php echo $this->locateFile('zIndexGenerator.js'); ?>"></script>
<?php endif; ?>
<?php
if ($config->searchbox->embeded)
    echo $this->partial('partials/jsSearchBox.phtml')
    ?>
<?php if (Zend_Registry::isRegistered('disabledFieldStatus') && !Zend_Registry::get('disabledFieldStatus')): ?>
    <script type="text/javascript" src="<?php echo $this->locateFile('manageChangedFields.js', null, 'back'); ?>"></script>
<?php endif; ?>
<?php echo $this->placeholder('footerScript');
?>
<script type="text/javascript">
    function ie8BeforeAfterFix(selectorString) {
        if ($('html').is('.ie8')) {
            var sel = selectorString || '.icon:before,.icon:after';
            var head = document.getElementsByTagName('head')[0],
                    style = document.createElement('style');
            style.type = 'text/css';
            style.styleSheet.cssText = sel + '{content:none !important}';
            head.appendChild(style);
            setTimeout(function() {
                head.removeChild(style);
            }, 0);
        }
    }
    $(window).on('load', function() {
        ie8BeforeAfterFix();
    })
    $(document).ready(function() {
        //polyfill activation
        $("[placeholder]").not('[data-sticky-ignore]').stickyPlaceholders();
        $("[placeholder][data-sticky-alt]").stickyPlaceholders({placeholderOpacity: 1});
        $('select').selectpicker();
        $('select').live('cible.creation', function() {
            $(this).selectpicker();
        })
        $('select').live('cible.destruction', function() {
            $(this).selectpicker('destroy');
        })
        $('select').live('cible.modification', function() {
            $(this).selectpicker('refresh');
        })
        $('[type=checkbox], [type=radio]').each(function() {
            $(this).prettyCheckable();
        });
        //script qui permet de rajouter des data-toggle sur des éléments html
        var options = {'eventsMap': [
                {'name': 'open', 'events': 'click', 'className': 'open', 'typeName': 'toggle', 'touch': true},
                {'name': 'modal', 'events': 'click', 'className': 'modal', 'typeName': 'modal', 'touch': true},
                {'name': 'collapse', 'events': 'click', 'className': 'collapse', 'typeName': 'collapse', 'touch': true},
                {'name': 'scroll', 'events': 'click', 'className': 'scroll', 'typeName': 'scroll', 'touch': true}
            ]};
//        $('html').cibletoggle(options);
        $('[type=number],[data-input-number]').inputNumber();
        $('[type=number],[data-input-number]').live('cible.creation', function() {
            $(this).inputNumber()
        })
        $('.site-parallax').scrolly();
        //ralentir la transition du collapse de bootstrap
        $.fn.collapse.Constructor.TRANSITION_DURATION = 750;
        //ajoute une classe empty lorsqu'un champ est vide
        setInterval(function() {
            $('input[type=text], textarea').each(function() {
                $this = $(this);
                $this.toggleClass('empty', ($this.val() == ""));
            });
        }, 100);
        //check le scroll
        $(window).scroll(function() {
            var $header = $('.site-header');
            var pos = $(window).scrollTop();
            var h = $header.outerHeight();
            $header.toggleClass('clinched', (pos > h));
        }).scroll();
        //check le resize
        $(window).resize(function() {
//            var $header = $('.site-header');
//            var $main = $('.site-main');
//            if($('body').is(':not(.home)')) {
//                $main.css('margin-top',$header.height());
//            }
        }).resize();
    });
</script>