<?php
$config = Zend_Registry::get("config");
$lang = $this->view->languageId;
$replace = array('<p>' => '', '<P>' => '', '</p>' => '', '</P>' => '', '%%%SITE_NAME%%%' => $config->site->title->$lang);
$imgAlt = $this->getClientText('home_page_link_title', null, $replace);
$imageFirstALT = "";
if (Zend_Registry::isRegistered('altImageFirst')) {
    $imageFirstALT = Zend_Registry::get('altImageFirst');
}
if ($imageFirstALT == "") {
    if (Zend_Registry::isRegistered('pageTitle')) {
        $imageFirstALT = Zend_Registry::get('pageTitle');
    } else if ($imgAlt != "") {
        $imageFirstALT = $imgAlt;
    } else {
        $imageFirstALT = $config->site->title->$lang;
    }
}
?>

<div class="site-header-container container">
    <div class="site-logo col-md-3">
        <?php
        $homeDetails = Cible_FunctionsPages::getHomePageDetails();
        $logo = $config->clientLogo->src;
        $logoContent = $config->clientLogo->src2;
        echo $this->link(
                $this->baseUrl() . '/' . $homeDetails['PI_PageIndex'], $this->clientImage($logo, array('alt' => $imageFirstALT)), array('title' => $imageFirstALT, 'class' => 'site-logo-image')
        );
        echo $this->link(
                $this->baseUrl() . '/' . $homeDetails['PI_PageIndex'], $this->clientImage($logoContent, array('alt' => $imageFirstALT)), array('title' => $imageFirstALT, 'class' => 'site-logo-image-content')
        );
        ?> 
    </div>
    <div class="site-header-collapse">
        <button class="site-header-collapse-button menu-collapse-button" data-toggle-collapse=".site-menu"></button>   
    </div>
    <div class="site-menu col-md-9 collapse">
        <nav class="site-menu-principal navbar navbar-default" role="navigation">
            <?php
            echo $this->menu(
                    'principal', array(
                'class' => 'nav navbar-nav',
                'id' => 'menu-principal',
                'maxLevel' => 3,
                'dropdownMenuClass' => 'dropdown-menu',
                'dropdownClass' => 'dropdown',
                'parentAltId' => 'parentIdTop-')
            );
            echo $this->languageSwitcher(array('use_suffix' => true));
            ?>
            <?php
            echo $this->menu(
                    'header', array(
                'class' => 'site-menu-icons nav navbar-nav',
                'id' => 'menu-secondaire',
                'isDropdownMenu' => true,
                'dropdownMenuClass' => 'dropdown-menu',
                'dropdownClass' => 'dropdown',
                'parentAltId' => 'parentIdTop-')
            );
            ?>
        </nav>
    </div>
</div>