<?php
$config = Zend_Registry::get("config");
$lang = $this->view->languageId;
$replace = array('<p>' => '', '<P>' => '', '</p>' => '', '</P>' => ''
    , '%%%SITE_NAME%%%' => $config->site->title->$lang);
$imgAlt = $this->getClientText('home_page_link_title', null, $replace);
$imageFirstALT = "";
if (Zend_Registry::isRegistered('altImageFirst')) {
    $imageFirstALT = Zend_Registry::get('altImageFirst');
}
if ($imageFirstALT == "") {
    if (Zend_Registry::isRegistered('pageTitle')) {
        $imageFirstALT = Zend_Registry::get('pageTitle');
    } else if ($imgAlt != "") {
        $imageFirstALT = $imgAlt;
    } else {
        $imageFirstALT = $config->site->title->$lang;
    }
}
$user = Zend_Registry::get('user');
$lnkAccount = $this->baseUrl() . '/' . Cible_FunctionsCategories::getPagePerCategoryView(1, 'become_client', 17, null, true);
?>
<div class="site-header-container container">
    <div class="site-name col-xs-1 col-md-4">
        <?php
        $homeDetails = Cible_FunctionsPages::getHomePageDetails();
        $logo = $config->clientLogo->src;
        echo $this->link(
                $this->baseUrl() . '/' . $homeDetails['PI_PageIndex'], $this->clientImage($logo, array('alt' => $imageFirstALT)), array('title' => $imageFirstALT, 'class' => 'site-logo')
        );
        ?>
    </div>
    <div class="cart-icon-data col-xs-1 col-md-1 pull-right">
        <?php $cartPage = '/' . Cible_FunctionsCategories::getPagePerCategoryView(0,
                'cart_details', 15, null, false); ?>
        <?php echo $this->link($this->baseUrl() . $cartPage,'<span class="icon-icon icon-cart"></span><span class="cart-icon-arrow"><span class="cart-item-count"></span></span>', array('class' =>'hidden')); ?>
    </div>
    <button aria-controls="navbar" aria-expanded="false" data-target='.site-menu-principal' data-toggle="collapse" class="navbar-toggle collapsed" type="button">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    </button>
    <nav class="site-menu-principal navbar navbar-default navbar-collapse collapse col-xs-12 col-md-7 pull-right" role="navigation">
        <?php
        echo $this->menu(
            'header', array(
            'class' => 'site-menu-icons nav navbar-nav',
            'id' => 'menu-secondaire',
            'isDropdownMenu' => true,
            'dropdownMenuClass' => 'dropdown-menu',
            'dropdownClass' => 'dropdown',
            'parentAltId' => 'parentIdTop-')
        );
//        echo $this->languageSwitcher(array('use_suffix' => true));
        ?>
        <br>
        <?php
        echo $this->menu(
            'principal', array(
            'class' => 'nav navbar-nav',
            'id' => 'menu-principal',
            'maxLevel' => 3,
            'dropdownMenuClass' => 'dropdown-menu',
            'dropdownClass' => 'dropdown',
            'parentAltId' => 'parentIdTop-')
        );
        ?>

<!--        <ul class="site-menu-icons site-menu-cart nav navbar-nav">
            <li class="">
                <a href="#" class="icon icon-cart">Cart</a>
                <span class="cart-number">3</span>
            </li>
        </ul>-->
        <!--    <ul class="navbar-form navbar-left" role="search" id="search-box">
                <li><input type="hidden" id="search-url" value="<? echo ($this->baseUrl()."/".Cible_FunctionsCategories::getPagePerCategoryView(0,'index',10)."/words");?>"/><input type="text" id="search-box-terme" name="search-box-terme" value="" /><a id="searchLink" href="#"><?php echo $this->clientImage('btn-search-' . Zend_Registry::get("languageSuffix") . '.png') ?></a></li>
            </ul>-->
    </nav>
        <?php if ($user): ?>
    <div class="sign-in logged col-xs-12 col-md-2">
        <?php echo $user['firstName'] . ' ' . $user['lastName']; ?><br>
        <?php echo $this->link($lnkAccount, 'Mon compte'); ?><br>
        <?php echo $this->link('javascript:logout();', $this->getClientText('account_logout_link'),array('class' => 'logout-btn')); ?>
        <?php else: ?>
    <div class="sign-in col-xs-12 col-md-2">
        <?php echo $this->link('#', $this->getCibleText('button_authenticate'), array('class' => 'login-btn')); ?>
    <?php endif; ?>
    </div>
</div>