<?php $data = $this->emailRenderData; ?>
<?php $config = Zend_Registry::get('config'); ?>
<html>
<head>
<meta http-equiv="content-language" content="fr"/>
<base href="<?php echo Zend_Registry::get('absolute_web_root') ?>" />
<title><?php echo $config->domainName; ?></title>

</head>
<body bgcolor="#FFFFFF" alink="#5D5D5C" vlink="#5D5D5C" link="#5D5D5C" text="#5D5D5C" topmargin="0" leftmargin="0" style="margin:0px;padding:0px;">

<table width="100%" border="0" cellspacing="0" cellpadding="0">
    <tr>
        <td align="center" valign="top">
            <table width="500" border="0" cellspacing="0" cellpadding="0">
                <tr>
                    <td align="center" valign="top">
                        <?php echo $data['emailHeader']; ?>
                    </td>
                </tr>
                <tr>
                    <td height="10">&nbsp;</td>
                </tr>
                <tr>
                    <td align="left" valign="top" style="color: #5D5D5C; font-size:12px; font-family:arial">
                        <?php echo $data['message']; ?>
                        <?php $list = implode('<br />', $data['list']);
                        echo $list; ?>
                        <?php if ($this->invalidEmailsList): ?>
                        <p>
                        Liste des emails invalides : <br />
                        <?php foreach ($this->invalidEmailsList as $invalid) :?>
                            <?php echo $invalid['fname']; ?> <?php echo $invalid['lname']; ?> : <?php echo $invalid['email']; ?> <br />
                        <?php endforeach;?>
                        </p>
                        <?php endif; ?>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td height="10">&nbsp;</td>
    </tr>
    <tr>
        <td height="10" align="center" valign="middle" style="border-top:3px dotted #E2E2E2">&nbsp;</td>
    </tr>
    <tr>
        <td bgcolor="#5FBBC9" height="35" align="center" valign="middle" style="color:#FFFFFF;">
            <?php echo str_replace('##SITE-NAME##', $config->domainName, $data['footer']); ?>
        </td>
    </tr>
</table>
</body>
</html>