<div class="block block-events">
    <?php if ($this->events): ?>

        <div class="title-others">AUTRES ÉVÉNEMENTS À VENIR...</div>

        <?php foreach($this->events as $event): ?>

            <div class="each-event">
                <?php
                    $date_string = '';
                    foreach($event['dates'] as $date){
                        $langSuffix = Zend_Registry::get('languageSuffix') . '_CA';
                        $startDate = new Zend_Date($date['EDR_StartDate'],null, $langSuffix);
                        $endDate = new Zend_Date($date['EDR_EndDate'],null, $langSuffix);

                        if( !empty($date_string) )
                            $date_string .= ' et ';

                        if( $startDate->get(Zend_Date::MONTH) == $endDate->get(Zend_Date::MONTH) && $startDate->get(Zend_Date::YEAR) == $endDate->get(Zend_Date::YEAR) ){
                            if( $startDate->get(Zend_Date::DAY) != $endDate->get(Zend_Date::DAY) )
                                $date_string .= sprintf("%d-%d %s %d", $startDate->get(Zend_Date::DAY), $endDate->get(Zend_Date::DAY), $startDate->get(Zend_Date::MONTH_NAME), $startDate->get(Zend_Date::YEAR));
                            else
                                $date_string .= sprintf("%d %s %d", $startDate->get(Zend_Date::DAY), $startDate->get(Zend_Date::MONTH_NAME), $startDate->get(Zend_Date::YEAR));
                        }
                        else
                            $date_string .= sprintf("%d %s %d au %d %s %d", $startDate->get(Zend_Date::DAY), $startDate->get(Zend_Date::MONTH_NAME), $startDate->get(Zend_Date::YEAR), $endDate->get(Zend_Date::DAY), $endDate->get(Zend_Date::MONTH_NAME), $endDate->get(Zend_Date::YEAR));
                    }
                ?>
                <div class="date"><a href="<?php echo $this->baseUrl() . '/' . $this->details_page . '/ID/' . $event['ED_ID'] ?>"><?php echo $date_string ?></a></div>
                <div class="title"><a href="<?php echo $this->baseUrl() . '/' . $this->details_page . '/ID/' . $event['ED_ID'] ?>"><?php echo $event['EI_Title'] ?></a></div>
                <div class="brief"><a href="<?php echo $this->baseUrl() . '/' . $this->details_page . '/ID/' . $event['ED_ID'] ?>"><?php echo $event['EI_Brief'] ?></a></div>
                <!--<div class="view-details"><?php echo $this->link( "{$this->baseUrl()}/{$this->details_page}/ID/{$event['ED_ID']}", $this->getClientText('see_details_news_text')) ?></div>-->
                <!--<div class="register"><?php echo $this->clientImage('button-register-event.jpg'); ?></div>-->
            </div>

            <div class="clear_both spacerMedium"></div>

        <?php endforeach; ?>


    <?php else: ?>
        <div>
        <?php if ($this->otherData): ?>
            <?php $options = array('type' => 'page', 'message' =>$this->getClientText('empty_data_disclaimer')); ?>
            <p><?php echo $this->languageSwitcher($options); ?></p>
        <?php else: ?>
            <p><?php echo $this->getCibleText('events_no_events') ?></p>
        <?php endif; ?>
        </div>
    <?php endif; ?>
</div>