<?php echo $this->showBlockTitle('h2'); ?>
<div class="block events2Cols">
   <div class="heightContainer">
    <?php
    $langSuffix = Cible_FunctionsGeneral::getLocalForLanguage(Zend_Registry::get("languageID"));
    if ($this->paginator):
        $count = 1;
        foreach ($this->paginator as $event):

            $class = '';

            $date = new Zend_Date($event['EDR_StartDate'], null, $langSuffix);
            $date_string_url = Cible_FunctionsGeneral::dateToString($date, Cible_FunctionsGeneral::DATE_SQL, '-');
            $date_string = Cible_FunctionsGeneral::dateToString($date, Cible_FunctionsGeneral::DATE_LONG, '.');
            $href = $event['URL'];

            $espace = $count % 2 ? 'espace' : '';
            ?>
            <div class="<?php echo $event['site']; ?>  events whiteBox2 <?php echo $espace; ?>">
                <?php //echo $this->link($href, '<img class="photo" width="289" height="193" src="../c3s/themes/images/common/img-events2.jpg">', array('title' => $this->getClientText('see_details_events_text'))); ?>

                <?php  if (!empty($event['NI_ImageSrc'])) : ?>
                        <?php
                        echo $this->link($href,
                            $this->eventsImage(
                                $event['ND_ID'],
                                $event['NI_ImageSrc'],
                                'thumb',
                                array(
                                    'class' => 'photo',
                                    'border' => '0',
                                )
                           )
                        );
                        ?>
                <?php  endif; ?>
                <div class="text">
                    <h6 class="events_title">
                        <?php // echo $this->link($href, $event['NI_Title'], array('title' => $this->getClientText('see_details_events_text'))); ?>
                        <?php echo $event['EI_Title']; ?>
                    </h6>
                    <?php
                    $date_string = '';
                    foreach($event['dates'] as $date){
                        $langSuffix = Zend_Registry::get('languageSuffix') . '_CA';
                        $startDate = new Zend_Date($date['EDR_StartDate'],null, $langSuffix);
                        $endDate = new Zend_Date($date['EDR_EndDate'],null, $langSuffix);

                        if( !empty($date_string) ){
                            $date_string .= $this->getCibleText('events_s_and_s');
                        }

                        if( $startDate->get(Zend_Date::MONTH) == $endDate->get(Zend_Date::MONTH) && $startDate->get(Zend_Date::YEAR) == $endDate->get(Zend_Date::YEAR) ){
                            if( $startDate->get(Zend_Date::DAY) != $endDate->get(Zend_Date::DAY) )
                                $date_string .= sprintf("%d-%d %s %d", $startDate->get(Zend_Date::DAY), $endDate->get(Zend_Date::DAY), $startDate->get(Zend_Date::MONTH_NAME), $startDate->get(Zend_Date::YEAR));
                            else
                                $date_string .= sprintf("%d %s %d", $startDate->get(Zend_Date::DAY), $startDate->get(Zend_Date::MONTH_NAME), $startDate->get(Zend_Date::YEAR));
                        }
                        else{
                            $dateElse = "%d %s %d" . $this->getCibleText('events_s_to_s') . "%d %s %d";
                            $date_string .= sprintf($dateElse, $startDate->get(Zend_Date::DAY), $startDate->get(Zend_Date::MONTH_NAME), $startDate->get(Zend_Date::YEAR), $endDate->get(Zend_Date::DAY), $endDate->get(Zend_Date::MONTH_NAME), $endDate->get(Zend_Date::YEAR));
                        }
                    }
                    ?>
                     <p class="date"><?php echo $date_string; ?></p>

                    <?php
                    $text = Cible_FunctionsGeneral::html2text($event['EI_BriefText']);
                    $text = Cible_FunctionsGeneral::truncateString($text, 150);

                    ?>
                    <p class="briefText">
                        <?php // echo $this->link($href, $event['NI_Title'], array('title' => $this->getClientText('see_details_events_text'))); ?>
                        <?php echo $text; ?>
                    </p>
                    <span class="suite_arrow">
                        <?php echo $this->link($href, $this->getClientText('see_details_events_text'), array('title' => $this->getClientText('see_details_events_text'))); ?>
                    </span>
                </div>
            </div>

            <?php if ($count % 2 == 0 ): ?>

                </div>
                <div class="heightContainer">
                <?php endif; ?>
                <?php $count++; ?>
        <?php endforeach; ?>
    </div>
        <div class="clear_both"></div>
        <?php echo $this->paginationControl($this->paginator, 'sliding', 'partials/products.paginator.phtml'); ?>
    <?php else: ?>
        <div>
        <?php if ($this->otherData): ?>
            <?php $options = array('type' => 'page', 'message' =>$this->getClientText('empty_data_disclaimer')); ?>
            <p><?php echo $this->languageSwitcher($options); ?></p>
        <?php else: ?>
            <p><?php echo $this->getCibleText('events_no_events') ?></p>
        <?php endif; ?>
        </div>
    <?php endif; ?>
</div>
<?php $this->placeholder('footerScript')->captureStart(); ?>
<script type="text/javascript">
//<![CDATA[
    $(document).ready(function(){

    $('.heightContainer').each(function(){
        var height = 0;
        $(this).find('.whiteBox2').each(function(){
            if ($(this).innerHeight() > height){
                height = $(this).innerHeight();
            }
        });
        $(this).find('.whiteBox2').each(function(){
            $(this).css('height', height);
        });
    });

    $('.events.whiteBox2').click(function(){
            window.location.href = $(this).find('a').attr('href');
        });
});
//]]>
</script>
<?php $this->placeholder('footerScript')->captureEnd(); ?>