
<section class="forms module forms-contact content">    
    <?php
    $inscriptionValidate = $this->inscriptionValidate;
    echo $this->showBlockTitle('h2', array('class' => 'forms-title content-h1-style super-margin-bottom'));

    if (!$inscriptionValidate) {
        echo($this->form);
        echo "<div class='champs-obligatoires'>".$this->getClientText('champs_obligatoires')."</div>";
    } else {
        ?>
        <p class="forms-contact-succeed">
            <?php
            echo($this->getClientText('form_contact_sent_tank_you_message'));
            ?>
        </p>
    <?php }
    ?>
    <div class="clear"></div>
</section>
<script>
    (function() {
        var submit = $('.forms-contact').find('.form-div-submit');
        var captcha = $('.forms-contact').find('.form-captcha-div')
        captcha.append(submit);
        $(window).resize(function(){
            $('.forms-contact').height($('.captcha-fieldset').height());
        })
    })();
</script>

