<section class="forms module forms-contact content">
    <?php
    $inscriptionValidate = $this->inscriptionValidate;
    echo $this->showBlockTitle('h2', array('class' => 'forms-title'));
    ?>
    <?php if (!$inscriptionValidate) :
        echo($this->form);
     else :
    ?>
    <p class="forms-contact-succeed">
    <?php echo($this->getClientText('form_contact_sent_tank_you_message'));?>
    </p>
    <?php endif; ?>
    <div class="clear"></div>
    <div class="required-field notice-required-field">
        <?php echo $this->getCibleText('form_field_required_label'); ?>
    </div>
</section>


