<?php
// loads the placeholders according to the number of zones
$emptyPlaceholders = $this->zonesBlocks(array('nbZones' => $this->nbZones));
?>
<div class="site-parallax-wrapper">
    <div class="site-parallax site-background" data-velocity=".8"></div>     
</div>
<div class="site-main-home-zone-1">
    <?php if (!isset($emptyPlaceholders[1])): ?>
        <!--<div id="zone1" class="">-->
        <?php echo $this->placeholder('zone1') ?>
        <!--</div>-->
    <?php endif; ?>
</div>
<div class="site-main-home-zone-2">
    <div class="site-main-home-zone-2-container container">   
        <div class="site-main-home-zone-2-content-wrapper col-lg-7">
            <?php if ($this->showTitle): ?>
                <h1 class="site-title"><?php echo $this->pageTitle()->toString(null, null, true) ?></h1>
            <?php endif; ?>    
            <?php if (!isset($emptyPlaceholders[2])): ?>
                <!--<div id="zone2" class="">-->
                <?php echo $this->placeholder('zone2') ?>
                <!--</div>-->
            <?php endif; ?>
        </div>
    </div>
</div>
<div class="site-main-home-zone-3 inverted">
    <div class="site-main-home-zone-3-container container">   
        <?php echo $this->placeholder('zone3'); ?>   
    </div>
</div>
