<?php
echo $this->partial('partials/header.pageDetails.phtml', array(
    'pageTitle' => $this->getCibleText('header_list_' . $this->actionKey . '_text'),
    'pageDescription' => $this->getCibleText('header_list_' . $this->actionKey . '_description'),
    'breadcrumb' => ''
));
?>

<div id="default_form">
    <div id="form_panel">
        <?php echo($this->mylist->render()); ?>
    </div>
</div>