<?php
// loads the placeholders according to the number of zones
$emptyPlaceholders = $this->zonesBlocks(array('nbZones' => $this->nbZones));
?>
<?php if (!empty($this->imgHeader)): ?>
<div class="site-banner" role="banner">
    <div class="site-banner-container container ">
        <?php echo $this->image($this->imgHeader, array('class' => 'img-header', 'direct' => true)); ?>
    </div>
</div>
<?php endif; ?>
<div class="site-main">
    <div class="site-main-contact-container container ">
        <?php if ($this->showTitle): ?>
            <h1 class="title col-md-12"><?php echo $this->pageTitle()->toString(null, null, true) ?></h1>
        <?php endif; ?>
        <main class="site-contact-zone-1 col-md-3">
            <?php if (!isset($emptyPlaceholders[1])): ?>
                <?php echo $this->placeholder('zone1') ?>
            <?php endif; ?>
        </main>
        <div class="site-contact-zone-2 col-md-9">
            <?php if (!isset($emptyPlaceholders[2])): ?>
                <?php echo $this->placeholder('zone2') ?>
            <?php endif; ?>
        </div>
    </div>
    <?php if (!isset($emptyPlaceholders[3])): ?>
    <div class="site-contact-zone-3">
        <?php echo $this->placeholder('zone3') ?>
    </div>
    <?php endif; ?>
</div>
