<?php
// loads the placeholders according to the number of zones
$emptyPlaceholders = $this->zonesBlocks(array('nbZones' => $this->nbZones));
?>
<?php if (!isset($emptyPlaceholders[7])): ?>
    <div class="site-banner inverted site-main-home-zone-7">
        <?php echo $this->placeholder('zone7') ?>
    </div>
<?php else: ?>
    <div class="site-banner inverted" role="banner">   
        <?php $src = $this->imgHeader; ?>
        <?php echo $this->image($this->imgHeader, array('class' => 'img-header', 'direct' => true)); ?>
    </div>
<?php endif; ?>
<div class="site-home-main-container container">        
    <div class="site-main-home-zone-1 col-md-12">
        <?php if (!isset($emptyPlaceholders[1])): ?>
            <!--<div id="zone1" class="">-->
            <?php echo $this->placeholder('zone1') ?>
            <!--</div>-->
        <?php endif; ?>
    </div>
    <div class="row">
        <div class="site-main-home-zone-2 col-md-6">
            <?php if ($this->showTitle): ?>
                <h1 class="site-title"><?php echo $this->pageTitle()->toString(null, null, true) ?></h1>
            <?php endif; ?>    
            <?php if (!isset($emptyPlaceholders[2])): ?>
                <!--<div id="zone2" class="">-->
                <?php echo $this->placeholder('zone2') ?>
                <!--</div>-->
            <?php endif; ?>
        </div>
        <div class="site-main-home-zone-3 col-md-6">
            <?php if (!isset($emptyPlaceholders[3])): ?>
                <!--<div id="zone3" class="">-->
                <?php echo $this->placeholder('zone3') ?>
                <!--</div>-->
            <?php endif; ?>
        </div>
    </div>
</div>
<div class="site-home-grey site-main-home-zone-4 inverted">
    <div class="site-home-grey-container container ">   
        <?php if (!isset($emptyPlaceholders[4])): ?>
            <!--<div id="zone4" class="">-->
            <?php echo $this->placeholder('zone4') ?>
            <!--</div>-->
        <?php endif; ?>
    </div>
</div>

<div class="site-home-blue blue-zone site-main-home-zone-5 inverted">
    <div class="site-home-blue-container container inverted">  
        <?php if (!isset($emptyPlaceholders[5])): ?>
            <!--<div id="zone5" class="">-->
            <?php echo $this->placeholder('zone5') ?>
            <!--</div>-->
        <?php endif; ?>
    </div>
</div>
<div class="site-home-bottom">
    <div class="site-home-bottom-container container">  
        <div class="site-main-home-zone-6 col-md-6">
            <?php if (!isset($emptyPlaceholders[6])): ?>
                <!--<div id="zone5" class="">-->
                <?php echo $this->placeholder('zone6') ?>
                <!--</div>-->
            <?php endif; ?>
        </div>
    </div>
</div>
